server:
  port: 8079

#Database configuration
spring:
  application:
    name: "apigateway-service"
  config:
    import: "configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

# To fetch updated property values as an when from cloud config
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  hostname: "localhost"
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"


info:
  app:
    name: "API Gateway Service"
    description: ""
    version: "1.0.0"

logging:
  level:
    com:
      kp:
        apigatewayserver: DEBUG
